"""Migration tests (T016).

The initial revision is written by hand, so the risk is not that Alembic is
broken -- it is that the revision and the models quietly disagree. Every test
here exists to make one specific way of disagreeing impossible to miss.

Two of them are worth singling out:

``test_empty_metadata_proposes_no_drops`` guards the failure mode that motivates
the explicit model import in ``migrations/env.py``. If ``target_metadata`` were
ever empty again, Alembic would compare an empty registry against a populated
database and propose dropping all 17 tables. It reports "success" while doing it.

``test_revision_ddl_matches_models`` compares compiled PostgreSQL DDL rather
than introspected attributes, because two declarations can be different objects
and identical statements. ``JSONB()`` and ``JSON().with_variant(JSONB(), ...)``
are such a pair, and so are ``sa.text("'{}'")`` and ``server_default="{}"``.
Only the rendered statement settles it.
"""

from __future__ import annotations

import subprocess
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest
import sqlalchemy as sa
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable

from app.config import reload_settings
from app.database.models.base import Base
from app.database.session import Base as SessionBase

SERVER_ROOT = Path(__file__).resolve().parents[2]
ALEMBIC_INI = SERVER_ROOT / "alembic.ini"
REVISION_ID = "0001_initial"

#: PostgreSQL is the authoritative store, so types are rendered for it. A
#: generic ``Uuid()`` compiles to ``CHAR(32)`` until a dialect is applied, which
#: would make every UUID column read as a difference.
DIALECT = postgresql.dialect()

#: The full schema, so a table added to the models without a migration is caught
#: and a table in the migration without a model is caught too.
EXPECTED_TABLES = {
    "users",
    "projects",
    "sessions",
    "tasks",
    "agents",
    "task_steps",
    "tool_executions",
    "conversations",
    "messages",
    "memories",
    "devices",
    "device_events",
    "events",
    "agent_logs",
    "model_usage",
    "audit_logs",
    "schedules",
}


class RecordingOperations:
    """Stands in for ``alembic.op`` so a revision can be run without a database.

    ``create_table`` receives columns *and* constraints in the same positional
    arguments, because Alembic's own ``CreateTableOp`` does too. Index columns
    arrive as bare strings in the revision, but as ``Column`` objects when
    autogenerated, so both are handled.
    """

    def __init__(self) -> None:
        self.tables: list[list[Any]] = []
        self.table_names: list[str] = []
        self.indexes: list[tuple[str, str, tuple[str, ...], bool]] = []
        self.dropped: list[str] = []
        self.executed: list[str] = []

    def create_table(self, name: str, *elements: Any, **_: Any) -> None:
        self.table_names.append(name)
        self.tables.append(list(elements))

    def create_index(
        self, name: str, table_name: str, columns: Any, unique: bool = False, **_: Any
    ) -> None:
        self.indexes.append(
            (table_name, name, tuple(c if isinstance(c, str) else c.name for c in columns), unique)
        )

    def drop_table(self, name: str, **_: Any) -> None:
        self.dropped.append(name)

    def execute(self, sql: str) -> None:
        self.executed.append(sql)


@pytest.fixture
def recorder() -> Iterator[RecordingOperations]:
    """Patch ``alembic.op`` and yield the recorder collecting a revision's calls."""
    from alembic import op

    recording = RecordingOperations()
    names = ("create_table", "create_index", "drop_table", "execute")
    saved = {name: getattr(op, name) for name in names}
    for name in names:
        setattr(op, name, getattr(recording, name))
    try:
        yield recording
    finally:
        for name, value in saved.items():
            setattr(op, name, value)


@pytest.fixture
def revision() -> Any:
    """The initial revision, loaded through Alembic's own script directory.

    Loading it the way Alembic does means the test is subject to the same
    ``down_revision`` wiring and script location the real command uses, rather
    than a hand-rolled import that could diverge from it.
    """
    config = ScriptDirectory.from_config(_alembic_config())
    script = config.get_revision(REVISION_ID)
    assert script is not None, f"{REVISION_ID} not found"
    assert script.module is not None
    return script.module


def _alembic_config() -> Any:
    from alembic.config import Config

    config = Config(str(ALEMBIC_INI))
    config.set_main_option("script_location", str(ALEMBIC_INI.parent / "migrations"))
    return config


def _scripts() -> Any:
    return ScriptDirectory.from_config(_alembic_config())


def _diff_kinds(diffs: list[Any]) -> set[str]:
    """The operation names in an autogenerate diff.

    Alembic returns tuples whose first element is a *list* of one string, so
    this is not a plain set comprehension -- ``diff[0]`` is unhashable.
    """
    kinds: set[str] = set()
    for diff in diffs:
        head = diff[0]
        if isinstance(head, list):
            kinds.update(str(item) for item in head)
        else:
            kinds.add(str(head))
    return kinds


def _run_upgrade(recording: RecordingOperations, module: Any) -> None:
    module.upgrade()


def _ddl(table: sa.Table) -> list[str]:
    return [
        " ".join(line.split())
        for line in str(CreateTable(table).compile(dialect=DIALECT)).splitlines()
        if line.strip()
    ]


def _revision_tables(recording: RecordingOperations) -> dict[str, sa.Table]:
    """Rebuild the revision's tables as real ``Table`` objects.

    All tables share one ``MetaData`` so foreign keys resolve: a key such as
    ``agent_logs.agent_id -> agents.id`` is only resolvable once the target table
    is present. The naming convention is copied from the models because Alembic
    does the same thing when it builds the ``MetaData`` for ``create_table``, and
    without it every primary and foreign key reads as unnamed.
    """
    metadata = sa.MetaData(naming_convention=Base.metadata.naming_convention)
    for name, elements in zip(recording.table_names, recording.tables, strict=True):
        sa.Table(name, metadata, *elements)
    return dict(metadata.tables)


class TestScriptWiring:
    def test_single_head(self) -> None:
        """Exactly one head, so there is no ambiguity about what ``head`` means."""
        assert list(_scripts().get_heads()) == [REVISION_ID]

    def test_initial_revision_has_no_parent(self, revision: Any) -> None:
        assert revision.down_revision is None

    def test_every_model_table_is_in_the_revision(
        self, revision: Any, recorder: RecordingOperations
    ) -> None:
        _run_upgrade(recorder, revision)
        assert set(recorder.table_names) == EXPECTED_TABLES

    def test_model_metadata_is_populated(self) -> None:
        """The precondition ``migrations/env.py`` exists to guarantee.

        If this fails, every other test in this file is comparing against a
        registry that is missing the models, and Alembic would be proposing to
        drop real tables.
        """
        assert set(Base.metadata.tables) == EXPECTED_TABLES

    def test_session_and_model_base_are_the_same_registry(self) -> None:
        """``Base`` must be one object, or ``target_metadata`` is the wrong one."""
        assert Base is SessionBase
        assert Base.metadata is SessionBase.metadata

    def test_env_module_excludes_alembic_version(self) -> None:
        """``include_object`` must never hand Alembic its own bookkeeping table."""
        source = (SERVER_ROOT / "migrations" / "env.py").read_text(encoding="utf-8")
        assert "alembic_version" in source
        assert _scripts().get_current_head() == REVISION_ID

    def test_alembic_ini_commits_no_credentials(self) -> None:
        """The DSN comes from settings, so the config file must not carry one."""
        text = ALEMBIC_INI.read_text(encoding="utf-8")
        assert "sqlalchemy.url" in text
        for line in text.splitlines():
            if line.strip().startswith("sqlalchemy.url"):
                assert line.strip() == "sqlalchemy.url =", line


class TestRevisionMatchesModels:
    def test_revision_ddl_matches_models(
        self, revision: Any, recorder: RecordingOperations
    ) -> None:
        """The authoritative check: identical compiled PostgreSQL DDL."""
        _run_upgrade(recorder, revision)
        rebuilt = _revision_tables(recorder)

        differences: list[str] = []
        for name in sorted(EXPECTED_TABLES):
            model_lines = _ddl(Base.metadata.tables[name])
            revision_lines = _ddl(rebuilt[name])
            for line in model_lines:
                if line not in revision_lines:
                    differences.append(f"{name}: model only -> {line}")
            for line in revision_lines:
                if line not in model_lines:
                    differences.append(f"{name}: revision only -> {line}")

        assert not differences, "\n".join(differences)

    def test_columns_match(self, revision: Any, recorder: RecordingOperations) -> None:
        _run_upgrade(recorder, revision)
        rebuilt = _revision_tables(recorder)

        problems: list[str] = []
        for name in sorted(EXPECTED_TABLES):
            model_names = set(Base.metadata.tables[name].columns.keys())
            revision_names = set(rebuilt[name].columns.keys())
            if model_names != revision_names:
                problems.append(
                    f"{name}: only in model {model_names - revision_names}, "
                    f"only in revision {revision_names - model_names}"
                )
                continue
            for column in sorted(model_names):
                left = Base.metadata.tables[name].columns[column]
                right = rebuilt[name].columns[column]
                if left.nullable != right.nullable:
                    problems.append(
                        f"{name}.{column}: nullable {left.nullable} != {right.nullable}"
                    )
                if left.primary_key != right.primary_key:
                    problems.append(f"{name}.{column}: primary_key differs")
        assert not problems, "\n".join(problems)

    def test_indexes_match(self, revision: Any, recorder: RecordingOperations) -> None:
        _run_upgrade(recorder, revision)

        revision_indexes = {
            (table, name, columns, unique) for table, name, columns, unique in recorder.indexes
        }
        model_indexes = {
            (table.name, index.name, tuple(c.name for c in index.columns), index.unique)
            for table in Base.metadata.tables.values()
            for index in table.indexes
        }
        assert revision_indexes == model_indexes

    def test_no_duplicate_indexes_per_table(
        self, revision: Any, recorder: RecordingOperations
    ) -> None:
        """No two indexes on one table may cover the same columns.

        An exact duplicate buys nothing and doubles write amplification on hot
        tables. One such pair existed during T016: ``parent_task_id`` carried both
        ``index=True`` and an explicit ``Index()`` of the same single column.
        """
        _run_upgrade(recorder, revision)

        problems: list[str] = []
        for table in Base.metadata.tables.values():
            by_columns: dict[tuple[str, ...], list[str]] = {}
            for index in table.indexes:
                by_columns.setdefault(tuple(c.name for c in index.columns), []).append(
                    index.name or "<unnamed>"
                )
            for columns, names in by_columns.items():
                if len(names) > 1:
                    problems.append(f"{table.name}{list(columns)}: {names}")
        assert not problems, "\n".join(problems)

    def test_least_privilege_columns_have_no_server_default(
        self, revision: Any, recorder: RecordingOperations
    ) -> None:
        """A tool call cannot be recorded without a level and a verdict.

        This is the schema-level half of the design: if these columns gained a
        default, an insert could omit the decision and the audit trail would
        acquire a hole exactly where it matters most.
        """
        _run_upgrade(recorder, revision)

        table = _revision_tables(recorder)["tool_executions"]
        for column in ("permission_level", "decision"):
            assert table.c[column].server_default is None, column
            assert table.c[column].nullable is False, column

    def test_audit_occurred_at_is_not_server_defaulted(self) -> None:
        """An audit row records when the operation was attempted, not when flushed."""
        assert Base.metadata.tables["audit_logs"].c["occurred_at"].server_default is None
        assert Base.metadata.tables["audit_logs"].c["occurred_at"].nullable is False


class TestNoDestructiveOperations:
    def test_empty_metadata_proposes_no_drops(self) -> None:
        """A populated ``target_metadata`` against a blank database drops nothing.

        The empty-registry failure is silent: Alembic connects, compares, finds
        17 tables it does not know about, and reports a perfectly successful run
        while proposing to drop all of them.
        """
        engine = sa.create_engine("sqlite://")
        with engine.connect() as connection:
            context = MigrationContext.configure(connection)
            diffs = compare_metadata(context, Base.metadata)
        engine.dispose()
        destructive = _diff_kinds(diffs) & {
            "remove_table",
            "drop_table",
            "remove_column",
            "remove_index",
        }
        assert not destructive, destructive

    def test_metadata_against_itself_is_empty(self) -> None:
        """A same-schema comparison must produce no structural operations.

        If this is non-empty the comparison is misconfigured, which would make
        the check above meaningless.
        """
        engine = sa.create_engine("sqlite://")
        Base.metadata.create_all(engine)
        with engine.connect() as connection:
            context = MigrationContext.configure(connection)
            diffs = compare_metadata(context, Base.metadata)
        engine.dispose()
        # SQLite reflects some types differently, so only table-level operations
        # are asserted on: those would mean the registries genuinely differ.
        structural = _diff_kinds(diffs) & {"add_table", "remove_table"}
        assert not structural, structural


class TestPgvectorBranch:
    def test_extension_and_vector_column_when_enabled(
        self, revision: Any, recorder: RecordingOperations, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setenv("ENABLE_PGVECTOR", "true")
        monkeypatch.setenv("EMBEDDING_DIMENSIONS", "768")
        reload_settings()
        _run_upgrade(recorder, revision)

        assert any("CREATE EXTENSION" in sql for sql in recorder.executed)
        column = _revision_tables(recorder)["memories"].c["embedding"]
        assert "VECTOR(768)" in str(column.type.compile(dialect=DIALECT))

    def test_jsonb_column_and_no_extension_when_disabled(
        self, revision: Any, recorder: RecordingOperations, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setenv("ENABLE_PGVECTOR", "false")
        reload_settings()
        _run_upgrade(recorder, revision)

        assert not any("CREATE EXTENSION" in sql for sql in recorder.executed)
        column = _revision_tables(recorder)["memories"].c["embedding"]
        assert "JSONB" in str(column.type.compile(dialect=DIALECT))

    def test_dimensions_are_read_from_settings(
        self, revision: Any, recorder: RecordingOperations, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A non-default width must reach the DDL, not just the default 768."""
        monkeypatch.setenv("ENABLE_PGVECTOR", "true")
        monkeypatch.setenv("EMBEDDING_DIMENSIONS", "1024")
        reload_settings()
        _run_upgrade(recorder, revision)

        column = _revision_tables(recorder)["memories"].c["embedding"]
        assert "VECTOR(1024)" in str(column.type.compile(dialect=DIALECT))


class TestDowngrade:
    def test_drops_every_table(self, revision: Any, recorder: RecordingOperations) -> None:
        _run_upgrade(recorder, revision)
        recorder.dropped.clear()
        revision.downgrade()
        assert set(recorder.dropped) == EXPECTED_TABLES

    def test_drops_in_reverse_dependency_order(
        self, revision: Any, recorder: RecordingOperations
    ) -> None:
        """Order is checked, not just membership.

        ``users`` and ``projects`` are referenced by nearly everything, so they
        have to go last; dropping them first would fail on the foreign keys.
        """
        _run_upgrade(recorder, revision)
        recorder.dropped.clear()
        revision.downgrade()

        positions = {name: index for index, name in enumerate(recorder.dropped)}
        assert positions["users"] > positions["sessions"]
        assert positions["projects"] > positions["agents"]
        assert positions["agents"] > positions["tool_executions"]
        assert positions["tasks"] > positions["task_steps"]
        assert positions["conversations"] > positions["messages"]
        assert positions["devices"] > positions["device_events"]

    def test_leaves_pgvector_extension_in_place(
        self, revision: Any, recorder: RecordingOperations
    ) -> None:
        """A downgrade must not drop an extension another schema may be using."""
        _run_upgrade(recorder, revision)
        recorder.executed.clear()
        revision.downgrade()
        assert not any("DROP EXTENSION" in sql.upper() for sql in recorder.executed)


@pytest.fixture(scope="module")
def offline_sql() -> str:
    """The rendered SQL from ``alembic upgrade head --sql``.

    Module-scoped and not a method: the subprocess takes a second or two, and it
    is the same output for every test that reads it.
    """
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head", "--sql"],
        cwd=SERVER_ROOT,
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    return result.stdout


class TestOfflineSql:
    """``alembic upgrade --sql`` is how a migration gets reviewed without a database."""

    def test_emits_every_table(self, offline_sql: str) -> None:
        for name in EXPECTED_TABLES:
            assert f"CREATE TABLE {name} " in offline_sql or f"CREATE TABLE {name} (" in offline_sql

    def test_emits_indexes(self, offline_sql: str) -> None:
        assert offline_sql.count("CREATE INDEX") >= 90
        assert "CREATE UNIQUE INDEX uq_messages_sequence" in offline_sql

    def test_contains_no_password(self, offline_sql: str) -> None:
        """The rendered SQL is the artifact most likely to be pasted into a ticket."""
        assert "u:p@" not in offline_sql
