"""Initial ULTRON schema: 17 tables (T016).

Creates the whole schema in dependency order. Written out explicitly rather than
autogenerated, because autogenerate emits what the models happen to say today
and gives no account of *why* -- and this is the revision every later one is
compared against.

Enum storage
------------
Enum-typed columns are ``VARCHAR`` holding the member **name**, not a native
PostgreSQL ``ENUM`` type. Two reasons, both deliberate:

- The member names appear in API payloads and event types, so they are part of
  the wire contract. A native enum renders its *value* in some contexts and its
  name in others, which makes the contract ambiguous.
- ``ALTER TYPE ... ADD VALUE`` on a native enum cannot run inside a transaction
  on PostgreSQL before 12, and even where it can, it cannot *remove* a value.
  Adding a status to ULTRON should not need a table lock.

The cost is that the database will accept a string that is not a member. That is
compensated for in three places rather than with ``CHECK`` constraints, which
would each need their own migration every time a member is added:

1. The Python side is a ``StrEnum``, so an invalid value fails on read rather
   than silently round-tripping.
2. Every repository that writes one of these columns takes the enum type as its
   parameter type, so the value is checked at the call site that has the context.
3. The membership of each enum is asserted in
   ``tests/unit/test_database_models.py``, so a value that is stored but cannot
   be reconstructed fails the test suite.

``tool_executions.permission_level`` and ``.decision`` are ``NOT NULL`` with no
server default, which is the schema-level half of the least-privilege design: a
tool call cannot be recorded without a level and a verdict.

Timestamps
----------
``created_at``/``updated_at`` use ``now()`` at the database, so a row's age does
not depend on which process clock wrote it. The exception is
``audit_logs.occurred_at``, which is ``NOT NULL`` with **no** default on purpose:
an audit row records when the operation was *attempted*, and a row that silently
stamped itself at flush time would misreport a decision that was made earlier.

pgvector
--------
``memories.embedding`` is created as ``VECTOR(768)`` when the pgvector extension
is available, and as ``JSONB`` when ``ENABLE_PGVECTOR=false``. The branch is on
the *migration*, not on the model, so the two cannot disagree about what the
column is -- a model that inferred its own column type from the environment
would mean the schema depended on an env var, and a database created with the
flag off could not be read by a process with it on.

``CREATE EXTENSION IF NOT EXISTS vector`` runs first and is the reason this
revision needs a role permitted to create extensions. The application role
should not hold that privilege, which is why the statement is written to be a
no-op when the extension is already present.

Revision ID: 0001_initial
Revises:
Create Date: 2026-01-01 00:00:00.000000+00:00
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID

from app.database.models.base import json_type

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _embedding_type(enable_pgvector: bool, dimensions: int) -> Any:
    """Return the column type for ``memories.embedding``.

    The one place in the migration where the target schema depends on
    configuration. See the module docstring.

    Returns ``Any`` for the same reason ``Memory._embedding_type`` does: pgvector
    is imported lazily so a deployment without the package still works when the
    extension is disabled, and an unimportable module cannot be type-checked.
    """
    if not enable_pgvector:
        # `json_type()`, not a bare JSONB: the model falls back to the same
        # variant type, and the two must be the same object for autogenerate to
        # see no drift.
        return json_type()
    from pgvector.sqlalchemy import Vector

    return Vector(dimensions)


def _create_pgvector(enable_pgvector: bool) -> None:
    """Create the pgvector extension if this revision is vector-backed.

    ``IF NOT EXISTS`` so a database where an operator already installed it is
    left alone. A failure here is not suppressed: if the flag says the schema
    needs vectors and the extension cannot be created, the migration must stop,
    because continuing would write the JSONB fallback into a column the rest of
    the system expects to be searchable.
    """
    if not enable_pgvector:
        return
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")


def upgrade() -> None:
    """Create the schema."""
    from app.config import get_settings

    settings = get_settings()
    dimensions = settings.embeddings.dimensions
    enable_pgvector = settings.database.enable_pgvector

    _create_pgvector(enable_pgvector)

    # --- users -------------------------------------------------------------
    # First: nearly everything references it.
    op.create_table(
        "users",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("is_superuser", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column(
            "is_service_account", sa.Boolean(), nullable=False, server_default="false"
        ),
        sa.Column("api_key_hash", sa.String(length=255), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("username", name="uq_users_username"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.UniqueConstraint("api_key_hash", name="uq_users_api_key_hash"),
    )
    op.create_index("ix_users_active", "users", ["is_active", "is_superuser"])
    op.create_index("ix_users_created_at", "users", ["created_at"])

    # --- projects ----------------------------------------------------------
    op.create_table(
        "projects",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("root_path", sa.String(length=1024), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("owner_id", UUID(as_uuid=True), nullable=True),
        sa.Column(
            "settings",
            json_type(),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("slug", name="uq_projects_slug"),
    )
    op.create_index("ix_projects_owner_id", "projects", ["owner_id"])
    op.create_index("ix_projects_created_at", "projects", ["created_at"])
    op.create_index("ix_projects_active_slug", "projects", ["is_active", "slug"])

    # --- sessions ----------------------------------------------------------
    op.create_table(
        "sessions",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # Hashes only. A stolen database must not yield usable tokens.
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "rotated_from",
            UUID(as_uuid=True),
            sa.ForeignKey("sessions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_reason", sa.String(length=128), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("token_hash", name="uq_sessions_token_hash"),
        sa.UniqueConstraint("refresh_token_hash", name="uq_sessions_refresh_token_hash"),
    )
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"])
    op.create_index("ix_sessions_expires_at", "sessions", ["expires_at"])
    op.create_index(
        "ix_sessions_user_active", "sessions", ["user_id", "revoked_at", "expires_at"]
    )

    # --- tasks -------------------------------------------------------------
    op.create_table(
        "tasks",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="pending"),
        sa.Column("priority", sa.String(length=16), nullable=False, server_default="normal"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "parent_task_id",
            UUID(as_uuid=True),
            sa.ForeignKey("tasks.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column(
            "result", json_type(), nullable=True
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("conversation_id", UUID(as_uuid=True), nullable=True),
        sa.Column("project_id", UUID(as_uuid=True), nullable=True),
        sa.Column("verification", sa.String(length=16), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("max_retries", sa.Integer(), nullable=False, server_default="3"),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("schedule_id", UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_tasks_status", "tasks", ["status"])
    op.create_index("ix_tasks_created_at", "tasks", ["created_at"])
    op.create_index("ix_tasks_completed_at", "tasks", ["completed_at"])
    op.create_index("ix_tasks_scheduled_for", "tasks", ["scheduled_for"])
    op.create_index("ix_tasks_schedule_id", "tasks", ["schedule_id"])
    op.create_index("ix_tasks_conversation_id", "tasks", ["conversation_id"])
    op.create_index("ix_tasks_project_id", "tasks", ["project_id"])
    op.create_index("ix_tasks_parent_task_id", "tasks", ["parent_task_id"])
    op.create_index("ix_tasks_dispatch", "tasks", ["status", "scheduled_for"])
    op.create_index("ix_tasks_project_status", "tasks", ["project_id", "status"])

    # --- agents ------------------------------------------------------------
    op.create_table(
        "agents",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("agent_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="created"),
        # SET NULL, not CASCADE: deleting a task must not delete the agent,
        # which may be reassignable and whose logs are the record of its work.
        sa.Column(
            "task_id",
            UUID(as_uuid=True),
            sa.ForeignKey("tasks.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column(
            "tools",
            json_type(),
            nullable=False,
            server_default="[]",
        ),
        sa.Column(
            "permissions",
            json_type(),
            nullable=False,
            server_default="[]",
        ),
        sa.Column("memory_namespace", sa.String(length=128), nullable=True),
        sa.Column("project_id", UUID(as_uuid=True), nullable=True),
        sa.Column(
            "parent_agent_id",
            UUID(as_uuid=True),
            sa.ForeignKey("agents.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_agents_agent_type", "agents", ["agent_type"])
    op.create_index("ix_agents_status", "agents", ["status"])
    op.create_index("ix_agents_task_id", "agents", ["task_id"])
    op.create_index("ix_agents_created_at", "agents", ["created_at"])
    op.create_index("ix_agents_memory_namespace", "agents", ["memory_namespace"])
    op.create_index("ix_agents_project_id", "agents", ["project_id"])
    op.create_index("ix_agents_status_type", "agents", ["status", "agent_type"])
    op.create_index("ix_agents_project_status", "agents", ["project_id", "status"])

    # --- task_steps --------------------------------------------------------
    op.create_table(
        "task_steps",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "task_id",
            UUID(as_uuid=True),
            sa.ForeignKey("tasks.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="pending"),
        sa.Column("attempt", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "depends_on",
            json_type(),
            nullable=False,
            server_default="[]",
        ),
        sa.Column("input_payload", json_type(), nullable=True),
        sa.Column("output_payload", json_type(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_task_steps_task_id", "task_steps", ["task_id"])
    op.create_index("ix_task_steps_status", "task_steps", ["status"])
    op.create_index("ix_task_steps_task_status", "task_steps", ["task_id", "status"])
    # Unique across attempts, not just position: a retry re-runs a step at the
    # same ordinal, and the attempt is what distinguishes the two rows.
    op.create_index(
        "uq_task_steps_position", "task_steps", ["task_id", "attempt", "position"], unique=True
    )

    # --- tool_executions ---------------------------------------------------
    op.create_table(
        "tool_executions",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "task_id",
            UUID(as_uuid=True),
            sa.ForeignKey("tasks.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("agent_id", UUID(as_uuid=True), nullable=True),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="pending"),
        # No server_default, and NOT NULL. This is the schema-level guarantee
        # that a tool call cannot be recorded without the level it ran at.
        sa.Column("permission_level", sa.String(length=32), nullable=False),
        # Likewise for the verdict itself.
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("input_payload", json_type(), nullable=True),
        sa.Column("output_payload", json_type(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("verification_outcome", sa.String(length=16), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
    )
    op.create_index("ix_tool_executions_task_id", "tool_executions", ["task_id"])
    op.create_index("ix_tool_executions_agent_id", "tool_executions", ["agent_id"])
    op.create_index("ix_tool_executions_tool_name", "tool_executions", ["tool_name"])
    op.create_index("ix_tool_executions_status", "tool_executions", ["status"])
    op.create_index("ix_tool_executions_request_id", "tool_executions", ["request_id"])
    op.create_index(
        "ix_tool_executions_task_tool", "tool_executions", ["task_id", "tool_name"]
    )

    # --- conversations -----------------------------------------------------
    op.create_table(
        "conversations",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="active"),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("project_id", UUID(as_uuid=True), nullable=True),
        sa.Column(
            "metadata",
            json_type(),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_conversations_user_id", "conversations", ["user_id"])
    op.create_index("ix_conversations_project_id", "conversations", ["project_id"])
    op.create_index("ix_conversations_status", "conversations", ["status"])
    op.create_index("ix_conversations_created_at", "conversations", ["created_at"])
    op.create_index("ix_conversations_last_message_at", "conversations", ["last_message_at"])
    op.create_index(
        "ix_conversations_project_status", "conversations", ["project_id", "status"]
    )

    # --- messages ----------------------------------------------------------
    op.create_table(
        "messages",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "conversation_id",
            UUID(as_uuid=True),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("role", sa.String(length=16), nullable=False, server_default="user"),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=True),
        sa.Column("tool_call_id", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("task_id", UUID(as_uuid=True), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_messages_conversation_id", "messages", ["conversation_id"])
    op.create_index("ix_messages_task_id", "messages", ["task_id"])
    op.create_index("ix_messages_request_id", "messages", ["request_id"])
    op.create_index(
        "uq_messages_sequence", "messages", ["conversation_id", "sequence"], unique=True
    )

    # --- memories ----------------------------------------------------------
    op.create_table(
        "memories",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("namespace", sa.String(length=255), nullable=False),
        # Parsed prefix, so the spec's "do not mix unrelated project memories"
        # is an indexed equality test rather than a substring match.
        sa.Column("namespace_kind", sa.String(length=32), nullable=False),
        sa.Column("namespace_slug", sa.String(length=255), nullable=False, server_default=""),
        sa.Column("layer", sa.String(length=16), nullable=False, server_default="long_term"),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", _embedding_type(enable_pgvector, dimensions), nullable=True),
        # Redundant with the column type on purpose: makes an embedding of the
        # wrong width detectable instead of silently unsearchable.
        sa.Column("vector_dimensions", sa.Integer(), nullable=True),
        sa.Column("importance", sa.Float(), nullable=False, server_default="0.5"),
        sa.Column("source_event_id", UUID(as_uuid=True), nullable=True),
        sa.Column("task_id", UUID(as_uuid=True), nullable=True),
        sa.Column("agent_id", UUID(as_uuid=True), nullable=True),
        sa.Column("user_id", UUID(as_uuid=True), nullable=True),
        sa.Column("project_id", UUID(as_uuid=True), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_memories_namespace", "memories", ["namespace"])
    op.create_index("ix_memories_scope", "memories", ["namespace_kind", "namespace_slug"])
    op.create_index("ix_memories_task_id", "memories", ["task_id"])
    op.create_index("ix_memories_agent_id", "memories", ["agent_id"])
    op.create_index("ix_memories_user_id", "memories", ["user_id"])
    op.create_index("ix_memories_project_id", "memories", ["project_id"])
    op.create_index("ix_memories_expires_at", "memories", ["expires_at"])
    op.create_index("ix_memories_layer_expires", "memories", ["layer", "expires_at"])
    op.create_index("ix_memories_user_created", "memories", ["user_id", "created_at"])

    # --- devices -----------------------------------------------------------
    op.create_table(
        "devices",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=True),
        sa.Column(
            "capabilities",
            json_type(),
            nullable=False,
            server_default="[]",
        ),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="unknown"),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("firmware_version", sa.String(length=64), nullable=True),
        sa.Column("auth_token_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "metadata",
            json_type(),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("auth_token_hash", name="uq_devices_auth_token_hash"),
    )
    op.create_index("ix_devices_type", "devices", ["type"])
    op.create_index("ix_devices_status", "devices", ["status"])
    op.create_index("ix_devices_last_seen", "devices", ["last_seen"])
    op.create_index("ix_devices_status_last_seen", "devices", ["status", "last_seen"])

    # --- device_events -----------------------------------------------------
    op.create_table(
        "device_events",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "device_id",
            UUID(as_uuid=True),
            sa.ForeignKey("devices.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", json_type(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("audio_path", sa.String(length=1024), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_device_events_device_id", "device_events", ["device_id"])
    op.create_index("ix_device_events_event_type", "device_events", ["event_type"])
    op.create_index("ix_device_events_received_at", "device_events", ["received_at"])
    op.create_index(
        "ix_device_events_device_received", "device_events", ["device_id", "received_at"]
    )

    # --- events ------------------------------------------------------------
    op.create_table(
        "events",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            json_type(),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("task_id", UUID(as_uuid=True), nullable=True),
        sa.Column("agent_id", UUID(as_uuid=True), nullable=True),
        sa.Column("user_id", UUID(as_uuid=True), nullable=True),
        sa.Column("project_id", UUID(as_uuid=True), nullable=True),
        sa.Column("device_id", UUID(as_uuid=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
    )
    op.create_index("ix_events_event_type", "events", ["event_type"])
    op.create_index("ix_events_occurred_at", "events", ["occurred_at"])
    op.create_index("ix_events_correlation_id", "events", ["correlation_id"])
    op.create_index("ix_events_task_id", "events", ["task_id"])
    op.create_index("ix_events_agent_id", "events", ["agent_id"])
    op.create_index("ix_events_type_time", "events", ["event_type", "occurred_at"])
    op.create_index("ix_events_task_time", "events", ["task_id", "occurred_at"])
    op.create_index(
        "ix_events_correlation", "events", ["correlation_id", "occurred_at"]
    )

    # --- agent_logs --------------------------------------------------------
    op.create_table(
        "agent_logs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "agent_id",
            UUID(as_uuid=True),
            sa.ForeignKey("agents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("task_id", UUID(as_uuid=True), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False, server_default="INFO"),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            json_type(),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("emitted_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_agent_logs_agent_id", "agent_logs", ["agent_id"])
    op.create_index("ix_agent_logs_task_id", "agent_logs", ["task_id"])
    op.create_index("ix_agent_logs_emitted_at", "agent_logs", ["emitted_at"])
    op.create_index(
        "ix_agent_logs_agent_sequence", "agent_logs", ["agent_id", "sequence", "emitted_at"]
    )

    # --- model_usage -------------------------------------------------------
    op.create_table(
        "model_usage",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="success"),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        # Numeric, never float: money must not accumulate binary rounding error.
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("task_id", UUID(as_uuid=True), nullable=True),
        sa.Column("agent_id", UUID(as_uuid=True), nullable=True),
        sa.Column("user_id", UUID(as_uuid=True), nullable=True),
        sa.Column("conversation_id", UUID(as_uuid=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_model_usage_model", "model_usage", ["model"])
    op.create_index("ix_model_usage_provider", "model_usage", ["provider"])
    op.create_index("ix_model_usage_request_id", "model_usage", ["request_id"])
    op.create_index("ix_model_usage_correlation_id", "model_usage", ["correlation_id"])
    op.create_index("ix_model_usage_task_id", "model_usage", ["task_id"])
    op.create_index("ix_model_usage_agent_id", "model_usage", ["agent_id"])
    op.create_index("ix_model_usage_user_id", "model_usage", ["user_id"])
    op.create_index("ix_model_usage_conversation_id", "model_usage", ["conversation_id"])
    op.create_index("ix_model_usage_recorded_at", "model_usage", ["recorded_at"])
    op.create_index("ix_model_usage_model_time", "model_usage", ["model", "recorded_at"])
    op.create_index("ix_model_usage_task_time", "model_usage", ["task_id", "recorded_at"])

    # --- audit_logs --------------------------------------------------------
    op.create_table(
        "audit_logs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        # No server_default, unlike every other timestamp here. An audit row
        # records when the operation was *attempted*; defaulting this to the
        # flush time would misreport a decision that was made earlier.
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "details",
            json_type(),
            nullable=False,
            server_default="{}",
        ),
    )
    op.create_index("ix_audit_logs_occurred_at", "audit_logs", ["occurred_at"])
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"])
    op.create_index("ix_audit_logs_request_id", "audit_logs", ["request_id"])
    op.create_index(
        "ix_audit_logs_resource", "audit_logs", ["resource_type", "resource_id"]
    )
    op.create_index(
        "ix_audit_logs_actor_action", "audit_logs", ["actor_type", "actor_id", "action"]
    )

    # --- schedules ---------------------------------------------------------
    op.create_table(
        "schedules",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False, server_default="interval"),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="active"),
        sa.Column("cron_expression", sa.String(length=128), nullable=True),
        sa.Column("interval_seconds", sa.Integer(), nullable=True),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "payload",
            json_type(),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("project_id", UUID(as_uuid=True), nullable=True),
        sa.Column("created_by_id", UUID(as_uuid=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_task_id",
            UUID(as_uuid=True),
            sa.ForeignKey("tasks.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("failure_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_schedules_project_id", "schedules", ["project_id"])
    op.create_index("ix_schedules_status", "schedules", ["status"])
    op.create_index("ix_schedules_next_run_at", "schedules", ["next_run_at"])
    op.create_index("ix_schedules_created_at", "schedules", ["created_at"])
    op.create_index("ix_schedules_due", "schedules", ["status", "next_run_at"])


def downgrade() -> None:
    """Drop the schema, in reverse dependency order.

    Drops the pgvector extension last, and only if this revision created it
    back to a count of zero other users -- the point being that a downgrade must
    not remove an extension another feature in the same database is relying on.
    """
    op.drop_table("schedules")
    op.drop_table("audit_logs")
    op.drop_table("model_usage")
    op.drop_table("agent_logs")
    op.drop_table("events")
    op.drop_table("device_events")
    op.drop_table("devices")
    op.drop_table("memories")
    op.drop_table("messages")
    op.drop_table("conversations")
    op.drop_table("tool_executions")
    op.drop_table("task_steps")
    op.drop_table("agents")
    op.drop_table("tasks")
    op.drop_table("sessions")
    op.drop_table("projects")
    op.drop_table("users")

    # Left in place deliberately: pgvector may be shared with other schemas in
    # the same database, and an extension is not ours to remove on the way out.
